# Generated by Django 4.0.1 on 2022-01-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaluser',
            old_name='type_of_user',
            new_name='role',
        ),
    ]
