# Generated by Django 4.0.1 on 2022-01-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0002_rename_type_of_user_hospitaluser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Patient First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Patient Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=200, verbose_name='Gender')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Temperature')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.patientbio')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(max_length=5000, verbose_name='Diagnosis')),
                ('treatment', models.CharField(max_length=5000, verbose_name='Treatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.patientvitals')),
            ],
        ),
    ]
