# Generated by Django 4.0.1 on 2022-01-24 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0003_patientbio_patientvitals_patientdiagnoses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbio',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='diagnostic',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.patientbio'),
        ),
        migrations.AlterField(
            model_name='patientdiagnoses',
            name='treatment',
            field=models.TextField(verbose_name='Treatment'),
        ),
    ]
