# Generated by Django 4.0.1 on 2022-01-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0005_alter_patientdiagnoses_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbio',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientdiagnoses',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientvitals',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
